# Generated by Django 4.0.2 on 2022-02-25 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user',
            new_name='owner',
        ),
    ]
