# Generated by Django 4.0.2 on 2022-02-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_alter_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('notStarted', 'NotStarted'), ('onGoing', 'OnGoing'), ('completed', 'Completed')], default='notStarted', max_length=20),
        ),
    ]
