# Generated by Django 4.0.2 on 2022-02-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_alter_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('notStarted', 'Not Started'), ('onGoing', 'On Going'), ('completed', 'Completed')], default='notStarted', max_length=15),
        ),
    ]
